/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author LABORATORIO UCV
 */
public class frmListaProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifBuscarEmp
     */
    public frmListaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListaProductos = new javax.swing.JTable();
        jbtnTodos = new javax.swing.JButton();
        jbtnBuscar = new javax.swing.JButton();
        jtxtTexto = new javax.swing.JTextField();
        jcbxCriterio = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblListaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 1020, 470));

        jbtnTodos.setText("TODOS");
        getContentPane().add(jbtnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 80, 46));

        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 90, 46));

        jtxtTexto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introduzca el texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(jtxtTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 70));

        jcbxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Producto", "Precio", "Categoria" }));
        jcbxCriterio.setSelectedIndex(1);
        jcbxCriterio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        getContentPane().add(jcbxCriterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnBuscar;
    public javax.swing.JButton jbtnTodos;
    public javax.swing.JComboBox<String> jcbxCriterio;
    public javax.swing.JTable jtblListaProductos;
    public javax.swing.JTextField jtxtTexto;
    // End of variables declaration//GEN-END:variables
}
