/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import javax.swing.UIManager;
/**
 *
 * @author LABORATORIO UCV
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public frmMenu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jpnlContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemmenu1_1 = new javax.swing.JMenu();
        menuRegProducto = new javax.swing.JMenuItem();
        menuRegCat = new javax.swing.JMenuItem();
        menuitem1_3 = new javax.swing.JMenuItem();
        menuitem1_4 = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        menuListaProducto = new javax.swing.JMenuItem();
        menuListaCat = new javax.swing.JMenuItem();
        menuitem2_3 = new javax.swing.JMenuItem();
        menuitem2_4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion con JDBC,DAO y MVC");

        jpnlContenedor.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpnlContenedorLayout = new javax.swing.GroupLayout(jpnlContenedor);
        jpnlContenedor.setLayout(jpnlContenedorLayout);
        jpnlContenedorLayout.setHorizontalGroup(
            jpnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        jpnlContenedorLayout.setVerticalGroup(
            jpnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        itemmenu1_1.setText("Mantenimiento");

        menuRegProducto.setText("Registro Productos");
        menuRegProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegProductoActionPerformed(evt);
            }
        });
        itemmenu1_1.add(menuRegProducto);

        menuRegCat.setText("Registro Categoria");
        menuRegCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegCatActionPerformed(evt);
            }
        });
        itemmenu1_1.add(menuRegCat);

        menuitem1_3.setText("Registro de Proveedores");
        itemmenu1_1.add(menuitem1_3);

        menuitem1_4.setText("Registro de Pedidos");
        itemmenu1_1.add(menuitem1_4);

        jMenuBar1.add(itemmenu1_1);

        menu2.setText("Ver");

        menuListaProducto.setText("Listar Productos");
        menu2.add(menuListaProducto);

        menuListaCat.setText("Listar Categorias");
        menu2.add(menuListaCat);

        menuitem2_3.setText("Listar Pedidos");
        menu2.add(menuitem2_3);

        menuitem2_4.setText("Buscar");
        menu2.add(menuitem2_4);

        jMenuBar1.add(menu2);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegProductoActionPerformed
       

    }//GEN-LAST:event_menuRegProductoActionPerformed

    private void menuRegCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegCatActionPerformed
       
        
    }//GEN-LAST:event_menuRegCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        
        try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}
        
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemmenu1_1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jpnlContenedor;
    private javax.swing.JMenu menu2;
    public javax.swing.JMenuItem menuListaCat;
    public javax.swing.JMenuItem menuListaProducto;
    public javax.swing.JMenuItem menuRegCat;
    public javax.swing.JMenuItem menuRegProducto;
    public javax.swing.JMenuItem menuitem1_3;
    public javax.swing.JMenuItem menuitem1_4;
    public javax.swing.JMenuItem menuitem2_3;
    public javax.swing.JMenuItem menuitem2_4;
    // End of variables declaration//GEN-END:variables
}
