/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author secacad-sistemas
 */
public class frmRegProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRegProducto
     */
    public frmRegProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jcbProveedor = new javax.swing.JComboBox<>();
        jbtnGrabar = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jtxtExistencia = new javax.swing.JTextField();

        setClosable(true);
        setTitle("REGISTRO PRODUCTO");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS  DEL PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCodigo.setForeground(new java.awt.Color(51, 51, 255));
        jtxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CODIGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 60));

        jtxtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(51, 51, 255));
        jtxtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 390, 70));

        jcbxCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbxCategoria.setForeground(new java.awt.Color(51, 51, 255));
        jcbxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jcbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jcbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 70));

        jcbProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbProveedor.setForeground(new java.awt.Color(51, 51, 255));
        jcbProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jcbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(jcbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 70));

        jbtnGrabar.setBackground(new java.awt.Color(204, 204, 255));
        jbtnGrabar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGrabar.setText("GRABAR");
        jPanel1.add(jbtnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 240, 50));

        jtxtCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCantidad.setForeground(new java.awt.Color(51, 51, 255));
        jtxtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cant. x Unidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 70));

        jtxtPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtPrecio.setForeground(new java.awt.Color(51, 51, 255));
        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 70));

        jtxtExistencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtExistencia.setForeground(new java.awt.Color(51, 51, 255));
        jtxtExistencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Existencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jtxtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 120, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCategoriaActionPerformed

    }//GEN-LAST:event_jcbxCategoriaActionPerformed

    private void jcbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProveedorActionPerformed

    }//GEN-LAST:event_jcbProveedorActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnGrabar;
    public javax.swing.JComboBox<String> jcbProveedor;
    public javax.swing.JComboBox<String> jcbxCategoria;
    public javax.swing.JTextField jtxtCantidad;
    public javax.swing.JTextField jtxtCodigo;
    public javax.swing.JTextField jtxtExistencia;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
