/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author j.j
 */
public class frmVerProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVerProducto
     */
    public frmVerProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtProveedor = new javax.swing.JTextField();
        jtxtCategoria = new javax.swing.JTextField();
        jtxtCantidad = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jtxtExistencia = new javax.swing.JTextField();
        jbtnCerrar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();

        setTitle("VER PRODUCTOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCodigo.setBackground(new java.awt.Color(153, 204, 255));
        jtxtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCodigo.setForeground(new java.awt.Color(51, 51, 255));
        jtxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CODIGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 70));

        jtxtNombre.setBackground(new java.awt.Color(0, 255, 255));
        jtxtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(51, 51, 255));
        jtxtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 390, 70));

        jtxtProveedor.setBackground(new java.awt.Color(153, 204, 255));
        jtxtProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtProveedor.setForeground(new java.awt.Color(51, 51, 255));
        jtxtProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.add(jtxtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 70));

        jtxtCategoria.setBackground(new java.awt.Color(153, 204, 255));
        jtxtCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCategoria.setForeground(new java.awt.Color(51, 51, 255));
        jtxtCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.add(jtxtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 70));

        jtxtCantidad.setBackground(new java.awt.Color(51, 204, 255));
        jtxtCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCantidad.setForeground(new java.awt.Color(51, 51, 255));
        jtxtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cant. x Unidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 70));

        jtxtPrecio.setBackground(new java.awt.Color(0, 255, 204));
        jtxtPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtPrecio.setForeground(new java.awt.Color(51, 51, 255));
        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, 70));

        jtxtExistencia.setBackground(new java.awt.Color(51, 255, 255));
        jtxtExistencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtExistencia.setForeground(new java.awt.Color(51, 51, 255));
        jtxtExistencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Existencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jtxtExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 120, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 370));

        jbtnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnCerrar.setText("CERRAR");
        getContentPane().add(jbtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 170, 50));

        jbtnActualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnActualizar.setText("ACTUALIZAR");
        getContentPane().add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 190, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void jtxtExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtExistenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnActualizar;
    public javax.swing.JButton jbtnCerrar;
    public javax.swing.JTextField jtxtCantidad;
    public javax.swing.JTextField jtxtCategoria;
    public javax.swing.JTextField jtxtCodigo;
    public javax.swing.JTextField jtxtExistencia;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField jtxtProveedor;
    // End of variables declaration//GEN-END:variables
}
